[package]
name = "numsc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "numsc"
path = "src/lib.rs"

[dependencies]
smol_str = "0.1.21"
num_enum = "0.5.7"
logos = "0.12.0"
